source("test/text.processing.tests.R")
source("test/ngrams.tests.R")
source("test/model.tests.R")
source("test/meta.model.tests.R")
source("test/global.tests.R")

text.processing.tests()
ngrams.tests()
model.tests()
meta.model.tests()
global.tests()
